# Generated by Django 6.0.5 on 2026-07-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_comment_author_message_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
