# Generated by Django 6.0.5 on 2026-06-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва фільму')),
                ('director', models.CharField(max_length=100, verbose_name='Режисер')),
                ('description', models.TextField(verbose_name='Опис')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('year', models.IntegerField(verbose_name='Рік випуску')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Фільм',
                'verbose_name_plural': 'Фільми',
                'ordering': ['-created_at'],
            },
        ),
    ]
