# Generated by Django 6.0.5 on 2026-06-09 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False, verbose_name='Переглянуто'),
        ),
    ]
